New root features
MoMEMta/MoMEMta pull request #181
Opened 2023-04-25 11:41 UTC by jtchk

2023-04-25 13:29 UTC, swertz requested changes
Thanks!

Could you just please add a meaningful description for your pull request?

Can you remove the empty `build.log` file from the PR?

Can you also bump the minimally supported ROOT version to 6.20.00 at these two places:
- https://github.com/MoMEMta/MoMEMta/blob/master/CMakeLists.txt#L86
- https://github.com/MoMEMta/MoMEMta/blob/master/README.md

2023-04-25 13:29 UTC, swertz commented on core/src/python/bindings.cc
> +    bp::list met_;
I don't understand how the MET is handled.

For the regular particles, you retrieve them from the `particles_` python list. But the `met_` list is just created here, while I think it should also be passed as an argument to the function?

2023-04-25 13:29 UTC, swertz commented on core/src/python/bindings.cc
> +    /*LorentzVector_to_python four_momentum_converter;*/
Can you remove this if it isn't used?

2023-04-26 12:52 UTC, jtchk commented on core/src/python/bindings.cc
> +    /*LorentzVector_to_python four_momentum_converter;*/
Lines 128-129 have been deleted from the `bindings.cc`file.

2023-04-26 13:16 UTC, swertz commented
Thanks again!

2023-04-26 13:16 UTC, swertz approved these changes
LGTM

2023-04-26 13:16 UTC, merged